### ISSUE TITLE
#Request nestedScrollEnabled

### ISSUE THREAD

**Issue by DeVoresyah** [zubairpaizer/react-native-searchable-dropdown#10]
Hello,
if the component inside the `ScrollView` or something like that, dropdown list not able to scroll. Right now I fixing that issue by adding `nestedScrollEnabled={true}` to `node_modules` folder.

It always be reset if I'm doing `npm install`
can you add `nestedScrollEnabled={true}` props to the main package?

thanks

**Comment by arjayosma** [comment]
you may want to do a pull request for your changes :D it'll be nice to have that as an addition

**Comment by zubairpaizer** [comment]
update package and pass via listProps = {{ nestedScrollEnabled: true }}
