### ISSUE TITLE
error Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by dimalahbal** [zubairpaizer/react-native-searchable-dropdown#11]
hello i get this error : 
Cannot read property 'toLowerCase' of undefined

how can i solve the problem

**Comment by amrita019** [comment]
Any update on this?

**Comment by zubairpaizer** [comment]
@amrita019 I think you pass a wrong structure to it

**Comment by Kojon74** [comment]
> @amrita019 I think you pass a wrong structure to it

Where is this problem being caused? I am running into the same issue.

Edit: Fixed my problem by going into the package code and searching for `toLowerCase`. Turns out my problem was occurring because one of the list items didn't have a `name` property thus `item.name` was giving undefined.
