### ISSUE TITLE
does not select the options

### ISSUE THREAD

**Issue by sakshamsd** [zubairpaizer/react-native-searchable-dropdown#16]
Cannot select the option from the list and also what if the list consists of 25000 data??

**Comment by ChathuraPrabhash** [comment]
Same issue here. can't select item when the picker in the Overlay(react-native-elements) or there have many elements in the component with the picker. But in a empty component(without any other element in the component) it works properly.

**Comment by Abhi-Tech9** [comment]
I guess it does not support selection when it is in scroll view. Did you guys manage to resolve it? 
@sakshamsd @ChathuraPrabhash

**Comment by zubairpaizer** [comment]
@sakshamsd now you can pass all FlatList props and you can also override its default props you can pass you paged data and changed it via data props in FlatList. you can manage 25000 list data like this
