### ISSUE TITLE
Search on Basis of Alphabetical Order

### ISSUE THREAD

**Issue by onizam95** [zubairpaizer/react-native-searchable-dropdown#19]
Need to have search on basis of Alphabetical Order. For Example it shouldn't be filtering on basis of LIKE but only searching on basis of alphabets in order from left to right. 
Like in case of countries if i search P i should all the names of countries starting from P not the entries which just contain P.
Please update what can be done in such a scenario.

**Comment by zubairpaizer** [comment]
you can pass your custom filter with setSort prop

**Comment by onizam95** [comment]
@zubairpaizer  the setSort Prop isn't working. Using the exact code as mentioned in docs but its still not working for alphabetical search
