### ISSUE TITLE
Search not working in 1.1.0

### ISSUE THREAD

**Issue by EricLewe** [zubairpaizer/react-native-searchable-dropdown#21]
I am using the example code provided in this repo, in 1.1.0 I am not able to search in the dropdown since the input immediately gets overwritten.

However if i downgrade to 1.0.6, searching works all fine. 

It is enough to reproduce this error by putting a <SearchableDropdown/>, get focus of it and start typing (in addition, example code in the readme also reproduces it).

**Comment by zubairpaizer** [comment]
fix on 1.1.1
