### ISSUE TITLE
Dropdown Fails to Collapse Upon Hiding the Keyboard

### ISSUE THREAD

**Issue by inf3rnus** [zubairpaizer/react-native-searchable-dropdown#25]
Hi, as the title says, the dropdown menu does not collapse when the keyboard is hidden, or when the screen is turned off. 

This can cause two issues.

Issue 1) - Depending on the styling rules you're using, hitting the hide keyboard button on the keyboard will show how the searchable drop-down has pushed the other flex boxes out of the way. Some people simply hide this issue by letting the keyboard cover up the messed up layout of the flexboxes below the searchable dropdown.

Issue 2) - Strange layout issues can occur if a searchable dropdown is left open when the screen of the device is turned off, as when you turn your screen back on, everything gets squished and mis aligned (Although it depends on the styling rules you're using.) I'm not exactly sure what's causing that aspect of it, but I'm lead to believe it's deleterious behavior and has something to do with the way React sets up flex boxes based off of how many components are taking up real estate on the screen. My pet theory is that your dropdown takes up space that wasn't there upon the initial render and upon a complete rerender (i.e. turning the device back on), I think the dimensions are altered from what they where when the page was rendered without the dropdown having been opened, that is, prior to having the device's screen turned off. 

I have confirmed this on Android and have fixed the issue in my own code by importing Keyboard from react and calling Keyboard.dismiss to force the Dropdown to collapse by responding to the dismissal event.

I did this by doing the following:

  _keyboardDidHide() {
    Keyboard.dismiss();
  }

  componentDidMount() {
    this.keyboardDidHideListener = Keyboard.addListener(
      'keyboardDidHide',
      this._keyboardDidHide,
    );
  }
  componentWillUnmount() {
    this.keyboardDidHideListener.remove();
  }

**Comment by inf3rnus** [comment]
If you think it's worthwhile, I'll create a pull request.

**Comment by Osama92** [comment]
I Had the same issue, it turned out that I had to hit the return button on the simulator to hide the dropdown. problem solved.
