### ISSUE TITLE
Require more values for defaultItemValue for API call

### ISSUE THREAD

**Issue by dhruvkeyal** [zubairpaizer/react-native-searchable-dropdown#26]
I'm using a custom API call to fetch values for the drop-down list.
The dummy endpoint I'm using is `https://aboutreact.com/demo/demosearchables.php` which works fine since it uses **id** and **name**.

However, when I'm trying to hit my endpoint, I want to use more values rather than just **id** and **name**. 

Whenever I try to do that, it gives me the following error:
`typeError: undefined is not an object (evaluating 'item.name')`.

Since defaultItemValue only takes in **name** and **id**, it seems to me that this is a restriction with the library and it can only use a JSON object with those two values in it.

Is anyone else experiencing the same issue and any thoughts on how to resolve it?

**Comment by RayhanYulanda** [comment]
The problem is when you call API i think. See this https://github.com/zubairpaizer/react-native-searchable-dropdown/issues/17#issuecomment-519785337
it's work for me
