### ISSUE TITLE
Issue with react-native version 

### ISSUE THREAD

**Issue by gudbrand3** [zubairpaizer/react-native-searchable-dropdown#27]
Hi,

I've upgraded to the latest react-native version 0.60.5. After doing that I am getting issues with the react-native-searchable-dropdown package and get the following warning. I have looked a bit and believe it is due to the version of react-native used in the package. When copying the code in a seperate js file using the project react-native dependency the issue is gone.

![Screenshot 2019-08-19 at 23 53 53](https://user-images.githubusercontent.com/12676373/63302184-c4b06900-c2dc-11e9-95c4-e272081d6a07.png)

Should be a quick fix I imagine, thanks :) great package!

**Comment by BravenxX** [comment]
Today I tried this package with:

    "react": "16.8.6",
    "react-native": "0.60.5",

And it works, I guess its fixed
