### ISSUE TITLE
Dropdown Item not Scrolling

### ISSUE THREAD

**Issue by yubarajoli77** [zubairpaizer/react-native-searchable-dropdown#28]
I use this lib to render the searchable dropdown inside flatlist. All works fine but dropdown items are not scrolling. While scrolling the dropdown parent flatlist scrolls instead.

**Comment by Robiullah2244** [comment]
I am facing the same problem. Anyone help us...

**Comment by Shan7anu** [comment]
@Robiullah2244 Did you make changes in index.js or in your component?

**Comment by Shan7anu** [comment]
@yubarajoli77 @Robiullah2244: Try passing below props to your component: 

```
listProps={{
    nestedScrollEnabled: true
}}
```
