### ISSUE TITLE
onBlur event

### ISSUE THREAD

**Issue by priami93** [zubairpaizer/react-native-searchable-dropdown#31]
It is possible to intercept onBlur event on inputField?

**Comment by zubairpaizer** [comment]
add support in 1.1.2
try this
        textInputProps={
          {
            placeholder: "placeholder",
            underlineColorAndroid: "transparent",
            style: {
                padding: 12,
                borderWidth: 1,
                borderColor: '#ccc',
                borderRadius: 5,
            },
            **onBlur: (e) => { 
              setSelectedItem(selectedItems);     
            },**
            onTextChange: text => console.log(text),
          }
        }
