### ISSUE TITLE
Clicking the items in the dropdown doesn't change the textbox input value

### ISSUE THREAD

**Issue by jlorencelim** [zubairpaizer/react-native-searchable-dropdown#4]
Whenever I click on the suggested items, it does not trigger the `onItemSelect` props.

**Comment by zubairpaizer** [comment]
It's triggering dude.

<img width="707" alt="screen shot 2018-07-06 at 11 06 51 am" src="https://user-images.githubusercontent.com/10752219/42362475-d848ee00-810c-11e8-8b50-ce7c44293bc1.png">

**Comment by ouatuandreea** [comment]
In index.js try:
 onBlur={() => {
              this.setState({ focus: true })
            }}

**Comment by skhumatine** [comment]
I don't like editing node modules but this seems to be a good work around for now. 
You can find onBlur

node_modules/react-native-searchable-dropdown/index.js:97

**Comment by HenryTux** [comment]
> > In index.js try:
> > onBlur={() => {
> > this.setState({ focus: true })
> > }}
> 
> This work around generates another problem: the list never disappear if you focus other input without selecting an item disappointed

True. I came across with this issue as well. I am currently using this component in a react-native-web project and before changing the focus value to true  as suggested (false by default), I would get the following error after selecting any item on the list. The list would hide and the TextInput would not update its value:

_Error: Unable to find node on an unmounted component._

Correct me if I am wrong but I presume it has something to do with the fact that at the time the list renders, the input is no longer focused and something behind that logic messes things up, the component cannot find the selected item and the error is triggered or something along those lines.

@matias91 try the following: 
```
onBlur={() => {
 setTimeout(() => this.setState({ focus: false }), 100) // no need to change it to true
}} 
```

You should be able to focus somewhere else and the list will hide.

I do not quite understand the behaviour of these events anyways (I am a beginner at React Native in fact haha), but I would not mind to discuss about this issue with you guys.

**Comment by matias91** [comment]
@HenryTux, Thanks for share your solution with us!

For the moment i'm using another component that fits better to my needs:
[react-native-sectioned-multi-select](https://github.com/renrizzolo/react-native-sectioned-multi-select)

Happy coding!

**Comment by devtechvalens** [comment]
Thanks ouatuandreea
onBlur={() => {
this.setState({ focus: true })
}} 

Worked for me

**Comment by saroj1982** [comment]
<SearchableDropdown
        onItemSelecte={item => console.log(item)}
        containerStyle={{ padding: 5 }}
        textInputStyle={{
          padding: 12,
          borderWidth: 1,
          borderColor: '#ccc',
          borderRadius: 5,
        }}
        itemStyle={{
          padding: 10,
          marginTop: 2,
          backgroundColor: '#ddd',
          borderColor: '#bbb',
          borderWidth: 1,
          borderRadius: 5,
        }}
        itemTextStyle={{ color: '#222' }}
        itemsContainerStyle={{ maxHeight: 140 }}
        items={items}
        defaultIndex={1}
        placeholder="Please enter the patient name"
        resetValue={false}
        underlineColorAndroid="transparent"
      />
 onItemSelecte={item => console.log(item)} ==this event is not firing

**Comment by saroj1982** [comment]
> It's triggering dude.
> 
> <img alt="screen shot 2018-07-06 at 11 06 51 am" width="707" src="https://user-images.githubusercontent.com/10752219/42362475-d848ee00-810c-11e8-8b50-ce7c44293bc1.png">

<SearchableDropdown
onItemSelecte={item => console.log(item)}
containerStyle={{ padding: 5 }}
textInputStyle={{
padding: 12,
borderWidth: 1,
borderColor: '#ccc',
borderRadius: 5,
}}
itemStyle={{
padding: 10,
marginTop: 2,
backgroundColor: '#ddd',
borderColor: '#bbb',
borderWidth: 1,
borderRadius: 5,
}}
itemTextStyle={{ color: '#222' }}
itemsContainerStyle={{ maxHeight: 140 }}
items={items}
defaultIndex={1}
placeholder="Please enter the patient name"
resetValue={false}
underlineColorAndroid="transparent"
/>
onItemSelecte={item => console.log(item)} ==this event is not firing

**Comment by arjayosma** [comment]
> > It's triggering dude.
> > <img alt="screen shot 2018-07-06 at 11 06 51 am" width="707" src="https://user-images.githubusercontent.com/10752219/42362475-d848ee00-810c-11e8-8b50-ce7c44293bc1.png">
> 
> <SearchableDropdown
> onItemSelecte={item => console.log(item)}
> containerStyle={{ padding: 5 }}
> textInputStyle={{
> padding: 12,
> borderWidth: 1,
> borderColor: '#ccc',
> borderRadius: 5,
> }}
> itemStyle={{
> padding: 10,
> marginTop: 2,
> backgroundColor: '#ddd',
> borderColor: '#bbb',
> borderWidth: 1,
> borderRadius: 5,
> }}
> itemTextStyle={{ color: '#222' }}
> itemsContainerStyle={{ maxHeight: 140 }}
> items={items}
> defaultIndex={1}
> placeholder="Please enter the patient name"
> resetValue={false}
> underlineColorAndroid="transparent"
> />
> onItemSelecte={item => console.log(item)} ==this event is not firing

you misspelled onItemSelect please check

**Comment by prasetiodc** [comment]
I got same problem. its doesnt work when **onItemSelect={item => console.log(item)}** but **onItemSelect={console.log("check")}** its work

**Comment by bumuthu** [comment]
I also have the same issue. 
onItemSelect={item => console.log(item)}. it doesnt trigger when selecting an item
any sollution?

**Comment by bumuthu** [comment]
Solved. Please visit...
https://stackoverflow.com/questions/59802634/react-native-component-searchabledropdown-from-react-native-searchable-dropdown/59803430#59803430

**Comment by bumuthu** [comment]
> I got same problem.
> **onItemSelect={item => console.log(item)}**. it doesnt work

Solved. Please visit...
https://stackoverflow.com/questions/59802634/react-native-component-searchabledropdown-from-react-native-searchable-dropdown/59803430#59803430

**Comment by michael-harley** [comment]
This is still not solved.

```
    "react": "16.9.0",
    "react-native": "0.61.4",
    "react-native-searchable-dropdown": "^1.1.1",
```

```
<SearchableDropdown
    onItemSelect={text => {
        alert(text);
        console.log('searchable', text);
    }
/>
```

**Comment by michael-harley** [comment]
I wrote a solution for this case.

https://github.com/michael-harley/react-native-searchable-dropdown

I assume the author isn't active anymore, as the last release for this repo is 7 months ago.

```
{
    "dependencies": {
        "react-native-searchable-dropdown": "https://github.com/michael-harley/react-native-searchable-dropdown",
    }
}
```

Use my link in your package.json, then install it.

**Comment by KaviduAloka** [comment]
Wrap it with a **ScrollView** and change the `ScrollView `  prop  `keyboardShouldPersistTaps='always'`

**Comment by vgaragozlu** [comment]
> I wrote a solution for this case.
> 
> https://github.com/michael-harley/react-native-searchable-dropdown
> 
> I assume the author isn't active anymore, as the last release for this repo is 7 months ago.
> 
> ```
> {
>     "dependencies": {
>         "react-native-searchable-dropdown": "https://github.com/michael-harley/react-native-searchable-dropdown",
>     }
> }
> ```
> 
> Use my link in your package.json, then install it.

This helped me man. Thank you muchhh ! However it becomes an issue when I do multi={true}. It doesnt allow multiple selections. :(

**Comment by vgaragozlu** [comment]
Guys, in my case the issue was in onItemSelect prop. I was pushing the item into the selectedItems array. However I had to actually just set the selectedItems object (not an array but should be an object) (So I changed my selectedItems initialization from an array to an object). I hope this helps someone.

**Comment by Shihaburabbi** [comment]
> I got same problem.
> **onItemSelect={item => console.log(item)}**. it doesnt work

I have Solve
 keyboardShouldPersistTaps = 'always'

**Comment by EkoSariyanto** [comment]
> I wrote a solution for this case.
> 
> https://github.com/michael-harley/react-native-searchable-dropdown
> 
> I assume the author isn't active anymore, as the last release for this repo is 7 months ago.
> 
> ```
> {
>     "dependencies": {
>         "react-native-searchable-dropdown": "https://github.com/michael-harley/react-native-searchable-dropdown",
>     }
> }
> ```
> 
> Use my link in your package.json, then install it.

work like charm, help my time

**Comment by DineshPrakasam** [comment]
> In index.js try: onBlur={() => { this.setState({ focus: true }) }

ok but i am using functional component , how can i code that, kindly help
