### ISSUE TITLE
In Flatlist selected item not reflected

### ISSUE THREAD

**Issue by NareshNama** [zubairpaizer/react-native-searchable-dropdown#5]
not working on Flatlist

**Comment by ayush12030** [comment]
@NareshNama I had faced a similar issue, mine was due to the fact that I had wrapped the SearchableDropdown component under my own scrollview component, which didn't have             keyboardShouldPersistTaps="always"

This question seems to be old, so maybe this might be helpful for someone else

**Comment by tayyabaAslam** [comment]
@ayush12030 thanks this fixed problem.

**Comment by gudbrand3** [comment]
@ayush12030 thanks this fixed my problem as well, should be added on read me for others which might struggle with the same, took a long time to figure out.

**Comment by alok0590** [comment]
@ayush12030 Thanks brother, You saved my couple of hours!

**Comment by yuriburk** [comment]
@ayush12030 thank you
