### ISSUE TITLE
Doesn't seem to work in web browser?

### ISSUE THREAD

**Issue by michael-fratta** [zubairpaizer/react-native-searchable-dropdown#68]
Hi there,

I can't find anyone else mentioning this so I'm wondering if it's just me, but - selecting an item seems to have no effect on state when running the app on a web browser? No alert is shown (or logged to the console). Have tried both Firefox and Chrome.

As an example, see: https://snack.expo.io/@aboutreact/searchable-dropdown?session_id=snack-session-CxUjYtYnj. This is not my app, but the result is the same i.e. when run in Web mode nothing happens when an item is selected, whereas when run in Android mode everything works as expected.

What gives? Is this an Expo bug or a package bug?

Many thanks,
Mike

**Comment by ShelterCode** [comment]
I am having same issue

**Comment by michael-fratta** [comment]
I'm closing this issue due to no response in 4+ months and realising that some things just don't work in a web browser (as they are not meant to).

**Comment by TDiblik** [comment]
Anybody found any alternatives?

**Comment by davidmartinrius** [comment]
> Anybody found any alternatives?

This one: https://github.com/danish1658/react-native-dropdown-select-list
