### ISSUE TITLE
clear inputfield 

### ISSUE THREAD

**Issue by Tobbb** [zubairpaizer/react-native-searchable-dropdown#8]
resetValue doesn't seem to  work for reseting the inputfield, after fetching new data the inputfield still have the old data in it, is there  a possible solution for this?

**Comment by arjayosma** [comment]
There's a `resetValue` prop, which can be set to TRUE or FALSE, but checking the source code, I can't seem to find it being used for resetting the input text. If author will not respond, maybe I'll submit a PR.
